name: PathwayBuilderPlugin
version: 1.0
main: com.ubivismedia.pathwaybuilder.PathwayBuilderPlugin
api-version: 1.20
description: Automatically build paths, bridges, and tunnels.
authors: [YourName]
website: https://github.com/your-repo
permissions:
  pathwaybuilder.admin:
    description: Allows access to all PathwayBuilderPlugin commands.
    default: op

commands:
  setpathpoint:
    description: Set a path point
    permission: pathwaybuilder.admin
  buildpath:
    description: Build a path between points
    permission: pathwaybuilder.admin
  undopath:
    description: Undo the last built path
    permission: pathwaybuilder.admin
