name: PathwayBuilderPlugin
version: 1.0
main: com.ubivismedia.pathwaybuilder.PathwayBuilderPlugin
api-version: 1.20
commands:
  setpathpoint:
    description: Set a path point
  buildpath:
    description: Build a path between points
  undopath:
    description: Undo the last built path
